### PR TITLE
Added National Day of Action Page w/ Twitter Campaign

### PR DESCRIPTION
**Pull request by hughdevore**
Hey Luke! 

Here is what we have so far. Let me know if you have any questions or if you would like us to change anything.
Thanks!! 

Hughie

### CODE REVIEW

**Comment by simplyluke** [comment]
@daveyoon I'll take a look at this before I sleep tonight and let you know if we're good to go for Austin. Let me know if National is okay with it. We'd like it up for the day of action (tomorrow).

**Comment by simplyluke** [comment]
I checked it out locally and it looks great to me. They did a great job this weekend. Responsive, polished. There's some more content we may add, but I'd love to get this up tomorrow AM for the day of action.

**Comment by hughdevore** [comment]
@simplyluke I've made the updates Nick requested. Let me know if y'all need anything else!

**Comment by daveyoon** [comment]
great work austin!

**Pull request merged**
